// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSJjgGfp-UpLJ7f7EDAgpYEaN7Qan9wqs',
    appId: '1:554656175883:web:d4a56dbc0a83760366740e',
    messagingSenderId: '554656175883',
    projectId: 'weatherapp-9eb1d',
    authDomain: 'weatherapp-9eb1d.firebaseapp.com',
    storageBucket: 'weatherapp-9eb1d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8pLhHuY-nTemoBoPiUAplDsqFG_F59R8',
    appId: '1:554656175883:android:913bbe13f7d2a5bd66740e',
    messagingSenderId: '554656175883',
    projectId: 'weatherapp-9eb1d',
    storageBucket: 'weatherapp-9eb1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8L00rxQnS2VXww7iW8RZMqmdd5wlvv4o',
    appId: '1:554656175883:ios:9b4d09e0aaa2a14666740e',
    messagingSenderId: '554656175883',
    projectId: 'weatherapp-9eb1d',
    storageBucket: 'weatherapp-9eb1d.firebasestorage.app',
    iosBundleId: 'com.example.aidreamteller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8L00rxQnS2VXww7iW8RZMqmdd5wlvv4o',
    appId: '1:554656175883:ios:9b4d09e0aaa2a14666740e',
    messagingSenderId: '554656175883',
    projectId: 'weatherapp-9eb1d',
    storageBucket: 'weatherapp-9eb1d.firebasestorage.app',
    iosBundleId: 'com.example.aidreamteller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSJjgGfp-UpLJ7f7EDAgpYEaN7Qan9wqs',
    appId: '1:554656175883:web:3b3d36c0d9a5680866740e',
    messagingSenderId: '554656175883',
    projectId: 'weatherapp-9eb1d',
    authDomain: 'weatherapp-9eb1d.firebaseapp.com',
    storageBucket: 'weatherapp-9eb1d.firebasestorage.app',
  );
}
